### PR TITLE
Added Battle for Wesnoth

### PR DESCRIPTION
**Pull request by Vultraz**

### CODE REVIEW

**Comment by Vultraz** [comment]
@DiscordAspekt just wondering, how come nothing is being merged here anymore? :(

**Comment by Vultraz** [comment]
Also pinging @jfurrow since the other guy might not be around anymore...

**Comment by jfurrow** [comment]
@Vultraz Sorry for the delay here. We realize we've dropped the ball here and are working toward a better long-term solution. Stay tuned, we should have some updates in this regard shortly!

**Comment by cooljeanius** [comment]
> Sorry for the delay here. We realize we've dropped the ball here and are working toward a better long-term solution. Stay tuned, we should have some updates in this regard shortly!

@jfurrow any news on these updates?

**Comment by Pentarctagon** [comment]
Any update on this?

**Comment by Vultraz** [comment]
Fixed the conflicts.

**Comment by Pentarctagon** [comment]
*pokes PR*

**Comment by BillyGalbreath** [comment]
> Stay tuned, we should have some updates in this regard shortly!

How long do we have to stay tuned?

**Review by cooljeanius — APPROVED** [review]

**Comment by cooljeanius** [comment]
Judging by recent commits, it looks like @devsnek is now the account merging stuff?

**Comment by Pentarctagon** [comment]
Closed since it's pretty clear that this repository is abandoned at this point.

**Pull request closed without merging**
