### PR TITLE
Add Starship

### PR DESCRIPTION
**Pull request by matchai**
https://github.com/starship/starship

Starship is the minimal, blazing fast, and extremely customizable prompt for any shell.
We have an active Discord community for collaborating on the development of Starship, and for people to drop in and get support.

### CODE REVIEW

**Comment by justinvforvendetta** [comment]
that sounds fun!

**Comment by matchai** [comment]
Hey @jamiebuilds! I went ahead and resolved conflicts on this PR.
Would it be possible to have it merged? 😊

**Comment by jamiebuilds** [comment]
Turned on some features for you:

- [Vanity Invite URL](https://support.discord.com/hc/en-us/articles/115001542132-Server-Vanity-URLs)
- [Server Banner & Invite Splash](https://support.discord.com/hc/en-us/articles/360028716472-Server-Banner-Background-Invite-Splash-Image)

Do you want to update your invite code to something like `discord.gg/<yourprojectname>`?

**Comment by matchai** [comment]
Thanks Jamie! I went ahead and updated the invite code to use the vanity URL. 😊

**Comment by jamiebuilds** [comment]
Thanks!

**Pull request merged**
