### PR TITLE
Added TitaniumNetwork

### PR DESCRIPTION
**Pull request by QuiteAFancyEmerald**
TitaniumNetwork is a community that hosts FOSS (open-source) projects on GitHub related to ending internet censorship in the form of web proxies.

Our community expects to provide users, and itself, with a less restrictive browsing experience. For this, web proxy sites such as Holy Unblocker have become the main services featured here. Over the course of the past couple years we have worked on various projects which have really increased the vast scale of the server.

Discord is mostly a place for us to hang out with the community and other swag individuals and to work on any future projects with other aspiring contributors; please direct any questions or concerns to our support and feedback channels.

Note this PR has been opened on the behalf of being a former staff member.

## Stats

Metrics - Reload if this doesn't appear as an embed

Discord Members: `14,580`

##

In order to make the review process faster, please take a few minutes to go through this checklist:

## Acceptance Criteria

- All of the following criteria must be met:
  - [x] This community is directly tied to an open source project
  - [x] The open source project has an OSI-approved open source license: https://opensource.org/licenses
  - [x] This Discord server is an official channel for the open source project approved by the maintainers of the open source project
  - [x] This Discord server adheres to the [Discord Community Guidelines](https://discord.com/guidelines)
- One of the following criteria must be met:
  - [x] The Discord server has over 1,000 members
  - [x] The open source project has a repository with at least 1,000 GitHub Stars or some equivalent (will forks count?)

## Code Review

- All of the following criteria must be met:
  - [x] The `"title"` field has a commonly identifiable name of the open source project
  - [x] The `"inviteCode"` field contains a valid invite code (without the full URL), without an expiration date
  - [x] The `"githubUrl"` field is a fully specified and valid URL starting with `https://` and refers to a place where we can easily find your primary open source repositories. GitHub repo or organization URLs (or some equivalent) are acceptable (but not a cloning URL).
  - [x] The `"logo"` field refers to the correct logo file (double-check the extension)
  - [x] The `"quote"` field (if included, it is optional) is about your usage of Discord (and not about the open source project itself)
  - [x] The `"quoteSourceUrl"` field (if included, it is optional) is a fully specified and valid URL starting with `https://`

## Logo Review

- All of the following criteria must be met:
  - [x] The logo makes use of transparent elements and does not include its own background
  - [x] The logo will look correct when the non-transparent elements are made solid white
  - [x] The logo is a commonly identifiable logo of the open source project
- One of the following criteria must be met:
  - [ ] The logo is an SVG file with 72x72 dimensions and has been optimized with [`svgo`](https://www.npmjs.com/package/svgo) ([Web UI](https://jakearchibald.github.io/svgomg/))
  - [x] The logo is a PNG file with 144x144 dimensions and has been optimized with [ImageOptim](https://imageoptim.com/) ([Web UI](https://imageoptim.com/online))

### CODE REVIEW

**Comment by captchaunited** [comment]
lean

**Review by captchaunited — APPROVED** [review]
I have throughout reviewed the content of this commit. 

# lean🥤💨🥱🍼

**Comment by Adithr123** [comment]
What is this?

**Comment by ctaetcsh** [comment]
Following some discussion that occurred on the Discord server, I thought it prudent to reflect some concerns some members (including myself) brought up that may affect the result of this PR.

1. TitaniumNetwork is not a singular open source project. Instead, it exists as a community and umbrella for other projects that may be independently managed.
2. The majority of the population of the server does not represent the open source community or show any interest in open source projects that fall under the TitaniumNetwork umbrella, with many (of their own admission) only being there to receive TN's services or to communicate with others about subjects unrelated to any open source project.

Given these facts, it's unclear if TN would be a good fit to be added to Discord's showcase of open source community servers, or if perusing this status would even be wise.

**Comment by captchaunited** [comment]
snitch bitc get stiche!! @ctaetcsh if u dont have anyting nice to say, dont say it at all

**Comment by QuiteAFancyEmerald** [comment]
Closed do to reconsideration. Sorry.

**Comment by ActuallyVys** [comment]
yeah its back!!!!!

**Pull request closed without merging**
