### PR TITLE
Added Blitz JS

### PR DESCRIPTION
**Pull request by nikolovlazar**
Adding Blitz JS's Discord Server. @flybayer check it out.

### CODE REVIEW

**Review by flybayer — APPROVED** [review]

**Comment by jamiebuilds** [comment]
Turned on some features for you:

- [Vanity Invite URL](https://support.discord.com/hc/en-us/articles/115001542132-Server-Vanity-URLs)
- [Server Banner & Invite Splash](https://support.discord.com/hc/en-us/articles/360028716472-Server-Banner-Background-Invite-Splash-Image)

Do you want to update your invite code to something like `discord.gg/<yourprojectname>`?

**Comment by flybayer** [comment]
@jamiebuilds thank you!!

@lazarnikolov94 can you update the invite code to `blitzjs` ?

**Comment by lazarnikolov94** [comment]
> @jamiebuilds thank you!!
> 
> 
> 
> @lazarnikolov94 can you update the invite code to `blitzjs` ?

Will do!

**Comment by lazarnikolov94** [comment]
@flybayer done! 🙌

**Review by jamiebuilds — APPROVED** [review]

**Comment by lazarnikolov94** [comment]
@jamiebuilds when is this going to be merged?

**Comment by jamiebuilds** [comment]
I'm still catching up on active PRs, it's easier for me to merge them in one big batch instead of asking people to rebase.

**Pull request closed without merging**
