### PR TITLE
add ZIO

### PR DESCRIPTION
**Pull request by softinio**

### CODE REVIEW

**Comment by softinio** [comment]
@jamiebuilds @faith Any chance you can help me move this forward to having a vanity URL etc also? 

This oss community was one of the first adopters of discord in the scala community. 

You can see promoted on its website: https://zio.dev/

Promoted on every single repo too: https://github.com/zio/zio

Thanks so much!

**Comment by faith** [comment]
> @jamiebuilds @faith Any chance you can help me move this forward to having a vanity URL etc also?
> 
> This oss community was one of the first adopters of discord in the scala community.
> 
> You can see promoted on its website: https://zio.dev/
> 
> Promoted on every single repo too: https://github.com/zio
> 
> Thanks so much!

Sure. Id recommend you contacting Discord at opensource@discord.com in the meanwhile

**Comment by softinio** [comment]
> > @jamiebuilds @faith Any chance you can help me move this forward to having a vanity URL etc also?
> > This oss community was one of the first adopters of discord in the scala community.
> > You can see promoted on its website: https://zio.dev/
> > Promoted on every single repo too: https://github.com/zio
> > Thanks so much!
> 
> Sure. Id recommend you contacting Discord at [opensource@discord.com](mailto:opensource@discord.com) in the meanwhile

@faith Just sent email like you suggested. Anything else I can help with to progress this let me know. Thanks for all help.

**Comment by faith** [comment]
> > > @jamiebuilds @faith Any chance you can help me move this forward to having a vanity URL etc also?
> > > This oss community was one of the first adopters of discord in the scala community.
> > > You can see promoted on its website: https://zio.dev/
> > > Promoted on every single repo too: https://github.com/zio
> > > Thanks so much!
> > 
> > Sure. Id recommend you contacting Discord at [opensource@discord.com](mailto:opensource@discord.com) in the meanwhile
> 
> @faith Just sent email like you suggested. Anything else I can help with to progress this let me know. Thanks for all help.

Probably typography in the official zio site even tho this shouldn't impact, just noticed that it was kinda not really the best 😂 no, probably nothing else tho

**Pull request closed without merging**
