### PR TITLE
add VergeCurrency Server (Discord Partner)

### PR DESCRIPTION
**Pull request by justinvforvendetta**
this pull request is for adding the Verge Community Discord Server!
https://vergecurrency.com
https://github.com/vergecurrency/
https://discord.gg/vergecurrency

### CODE REVIEW

**Comment by justinvforvendetta** [comment]
@DiscordAspekt

**Comment by justinvforvendetta** [comment]
@jfurrow ? hope all is well.

**Comment by qaisjp** [comment]
> (should consider changing from travis to circle-ci btw)

GitHub Actions

**Comment by justinvforvendetta** [comment]
@qaisjp yes or github actions =]

**Comment by qaisjp** [comment]
Unfortunately it seems that this repository has been abandoned :(

**Comment by justinvforvendetta** [comment]
i thought that the site was being served from this repo

**Comment by justinvforvendetta** [comment]
@jfurrow is the site still being served from here or ?

**Comment by BenjaminForster** [comment]
> Unfortunately it seems that this repository has been abandoned :(

No, this repository was last updated February.

**Comment by justinvforvendetta** [comment]
@jamiebuilds just updated this after your last commit for starship, peep it if you get a sec =]

**Comment by justinvforvendetta** [comment]
see https://github.com/discord/discord-open-source/pull/307

**Pull request closed without merging**
