### PR TITLE
Add Files

### PR DESCRIPTION
**Pull request by yaichenbaum**
[Files](https://github.com/files-community/Files) community discord server.
https://discord.gg/mr5hVu8

### CODE REVIEW

**Comment by jamiebuilds** [comment]
Turned on some features for you:

- [Vanity Invite URL](https://support.discord.com/hc/en-us/articles/115001542132-Server-Vanity-URLs)
- [Server Banner & Invite Splash](https://support.discord.com/hc/en-us/articles/360028716472-Server-Banner-Background-Invite-Splash-Image)

If you'd like, you can go update your invite code to something like `discord.gg/<yourprojectname>` and then update it in this PR. Either way, please let me know.

**Comment by yaichenbaum** [comment]
@jamiebuilds Thanks!

**Review by jamiebuilds — APPROVED** [review]

**Comment by sylveon** [comment]
@jamiebuilds is it possible to enable banners and invite splash for existing communities in the list?

**Comment by yaichenbaum** [comment]
@jamiebuilds can we get this merged?

**Comment by yaichenbaum** [comment]
@devsnek can we get this merged?

**Pull request closed without merging**
