### PR TITLE
mcMMO community and logo

### PR DESCRIPTION
**Pull request by nossr50**
mcMMO is an open source project over 8 years old, recently I started an official discord for mcMMO and it has reached over 1000 members.

I'd love for the mcMMO guild to be part of the open source communities for Discord.

EDIT: Main Repo: https://github.com/mcMMO-Dev/mcMMO

### CODE REVIEW

**Comment by nossr50** [comment]
We are still interested in joining the open source communities for discord ❤️

**Comment by Chew** [comment]
Hey @jamiebuilds, I saw #303 got perks from this, is there a different requirement that needs to be met for them to be added here?

**Comment by jamiebuilds** [comment]
>  is there a different requirement that needs to be met for them to be added here?

Nope, this PR just predated when I got permission to toggle on these features for servers in this repository.

**Comment by jamiebuilds** [comment]
Turned on some features for you:

- [Vanity Invite URL](https://support.discord.com/hc/en-us/articles/115001542132-Server-Vanity-URLs)
- [Server Banner & Invite Splash](https://support.discord.com/hc/en-us/articles/360028716472-Server-Banner-Background-Invite-Splash-Image)

Do you want to update your invite code to something like `discord.gg/<yourprojectname>`?

**Comment by nossr50** [comment]
@jamiebuilds thanks, our vanity code is discord.gg/mcmmo and it can be updated to that
Is the verified checkmark not part of this?

**Comment by jamiebuilds** [comment]
Do you mean the [server verification program](https://discord.com/verification)? That has some additional requirements and you'll have to apply through that program directly.

**Pull request merged**
