### PR TITLE
Added Poimandres

### PR DESCRIPTION
**Pull request by stephencorwin**
[Poimandres](https://github.com/pmndrs) is a developer collective building tools for the creative space including popular libaries like [React Spring](https://github.com/pmndrs/react-spring) and [React Three Fiber](https://github.com/pmndrs/react-three-fiber/).

[Discord Shield](https://discord.gg/ZZjjNvJ)

### CODE REVIEW

**Comment by jamiebuilds** [comment]
Awesome :) We use a couple of these libraries to build Discord. Would you mind rebasing this PR though? Really need to create a better format to not create so many git conflicts 😅

**Comment by stephencorwin** [comment]
@jamiebuilds should be good now. Thanks!

**Comment by jamiebuilds** [comment]
Turned on some features for you:

- [Vanity Invite URL](https://support.discord.com/hc/en-us/articles/115001542132-Server-Vanity-URLs)
- [Server Banner & Invite Splash](https://support.discord.com/hc/en-us/articles/360028716472-Server-Banner-Background-Invite-Splash-Image)

Do you want to update your invite code to something like `discord.gg/<yourprojectname>`?

**Comment by stephencorwin** [comment]
Awesome! 🎉
I updated the commit

**Comment by gsimone** [comment]
Thanks Jamie! 🎊

**Comment by jamiebuilds** [comment]
Thanks!

**Pull request merged**
