### PR TITLE
Add Scala

### PR DESCRIPTION
**Pull request by softinio**

### CODE REVIEW

**Comment by faith** [comment]
They should be partnered with discord im pretty sure as its for official open source communities using it.

**Comment by softinio** [comment]
@faith whats the process to apply for a partner? Thanks!

**Comment by faith** [comment]
> @faith whats the process to apply for a partner? Thanks!

https://discord.com/partners. I check Scala language website and i didn't find it which leaves me to believe this is a community server, this is mostly for official servers adopted by those developers, this means if developers do decide to adopt it then yes. I am not sure about this, maybe there is exceptions but thats the case for the most part.

**Comment by softinio** [comment]
@faith thanks for the info. It is the official discord server they just haven't added it to their website yet. Will discuss Partner option with them in parallel to hoping this PR gets merged in the meanwhile.

**Comment by jamiebuilds** [comment]
Turned on some features for you:

- [Vanity Invite URL](https://support.discord.com/hc/en-us/articles/115001542132-Server-Vanity-URLs)
- [Server Banner & Invite Splash](https://support.discord.com/hc/en-us/articles/360028716472-Server-Banner-Background-Invite-Splash-Image)

Do you want to update your invite code to something like `discord.gg/<yourprojectname>`?

**Comment by faith** [comment]
Nevermind to apply for partner as open source project u must email opensource@discord.com. @jamiebuilds has said that he enabled that for you but it doesn't look like it atleast from what i have checked, congrats if so 😝

**Comment by SethTisue** [comment]
> they just haven't added it to their website yet

I have now done so here: https://github.com/scala/scala-lang/pull/1189

The change now shows up here: https://www.scala-lang.org/community/#chat-rooms-discord-irc

**Comment by SethTisue** [comment]
> Do you want to update your invite code to something like discord.gg/<yourprojectname>?

Yes please, `discord.gg/scala` would be fantastic

**Comment by faith** [comment]
> > they just haven't added it to their website yet
> 
> I have now done so here: [scala/scala-lang#1189](https://github.com/scala/scala-lang/pull/1189)
> 
> The change now shows up here: https://www.scala-lang.org/community/#chat-rooms-discord-irc

Awesome, also i made a pull request, i was talking about socials on the index page, it can be found at https://github.com/scala/scala-lang/pull/1190

**Comment by softinio** [comment]
@faith @jamiebuilds Thank you so much for helping to push this through. 

Do we still need to email opensource@discord.com or no need now? 

Also, do I need to make any changes to this PR for the vanity `discord.gg/scala` url ? 

Thanks.

cc @SethTisue

**Comment by jamiebuilds** [comment]
You can apply to the partner program if you'd like, there are some other features I think there for you.

But to setup the vanity URL you need to set it up inside of Discord. Docs: [Vanity Invite URL](https://support.discord.com/hc/en-us/articles/115001542132-Server-Vanity-URLs)

Then you can update it in this PR

**Comment by softinio** [comment]
@jamiebuilds Vanity URL set and PR updated. Anything else do we need to so or are we ready for merge? 

@SethTisue Leave it to you decide if we should apply for the partner program. Let me know if I can help or you are handling it.

Thanks All.

**Comment by SethTisue** [comment]
> Leave it to you decide if we should apply for the partner program. Let me know if I can help or you are handling it.

I'll look into it (next week, most likely)

**Comment by softinio** [comment]
@SethTisue Scala website updated with vanity url PR: https://github.com/scala/scala-lang/pull/1192

**Comment by softinio** [comment]
@jamiebuilds Vanity URL setup and this PR updated.

Let me know if there is anything else you need from me to move forward with this PR.

Thank you.

**Comment by jamiebuilds** [comment]
Thanks!

**Pull request merged**
