### PR TITLE
Adding Chakra UI

### PR DESCRIPTION
**Pull request by nikolovlazar**
Adding Chakra UI's Discord server. Ping @segunadebayo

### CODE REVIEW

**Comment by jamiebuilds** [comment]
Turned on some features for you:

- [Vanity Invite URL](https://support.discord.com/hc/en-us/articles/115001542132-Server-Vanity-URLs)
- [Server Banner & Invite Splash](https://support.discord.com/hc/en-us/articles/360028716472-Server-Banner-Background-Invite-Splash-Image)

Do you want to update your invite code to something like `discord.gg/<yourprojectname>`?

**Comment by lazarnikolov94** [comment]
I've added the Vanity Invitation URL @jamiebuilds! Ready to go 🙌

**Review by jamiebuilds — APPROVED** [review]

**Comment by lazarnikolov94** [comment]
@jamiebuilds when is this going to be merged?

**Comment by jamiebuilds** [comment]
I'm still catching up on active PRs, it's easier for me to merge them in one big batch instead of asking people to rebase.

**Pull request closed without merging**
