### PR TITLE
Add Oh My Zsh

### PR DESCRIPTION
**Pull request by larson-carter**
I have followed the proper steps to adding Oh My Zsh to the discord for open source program!

### CODE REVIEW

**Comment by larson-carter** [comment]
It appears that some invite codes can not be found:

Augur (faud6Fx): { message: 'Unknown Invite', code: 10006 }
Ubiq (RkPDGe6): { message: 'Unknown Invite', code: 10006 }
Relay (A5KakZH): { message: 'Unknown Invite', code: 10006 }
Nano Currency (JphbBas): { message: 'Unknown Invite', code: 10006 }
PIVX (ktYKb32): { message: 'Unknown Invite', code: 10006 }
Songoda (JabJmbe): { message: 'Unknown Invite', code: 10006 }
IntellectualSites (ngZCzbU): { message: 'Unknown Invite', code: 10006 }
Failed to validate invite codes
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-open-source@1.0.0 validate-codes: `node ./validate.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the discord-open-source@1.0.0 validate-codes script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2020-06-09T17_38_34_045Z-debug.log
npm ERR! Test failed.  See above for more details.

**Review by MagnusDot — APPROVED** [review]
For me Oh My Zsh is a good open source improvement for the discord community !

**Review by 4ldas — CHANGES_REQUESTED** [review]
Replace the invite with vanity invite of "OhMyZsh"

**Comment by larson-carter** [comment]
Closing as this has been inactive for over 4+ years. If it needs to be reopened I can do so.

**Pull request closed without merging**
