### PR TITLE
Add ViaVersion

### PR DESCRIPTION
**Pull request by FormallyMyles**
Added ViaVersion to the list.

Project's download page - https://viaversion.com
Main repo - https://github.com/ViaVersion/ViaVersion

Let me know if anything else is needed (or if I went wrong with the SVG), <3 you guys.

### CODE REVIEW

**Comment by UnknownHacker1125** [comment]
You need to have 1000 stars.

**Comment by MylesIsCool** [comment]
> You need to have 1000 stars.

Your community has at least 1,000 members, or the GitHub repo has at least 1,000 stars.

The discord has over 1000 members so it fits the member requirement.

**Comment by FormallyMyles** [comment]
@jamiebuilds Would we be able to get access to the vanity url / banner / splash?

**Comment by jamiebuilds** [comment]
Turned on some features for you:

- [Vanity Invite URL](https://support.discord.com/hc/en-us/articles/115001542132-Server-Vanity-URLs)
- [Server Banner & Invite Splash](https://support.discord.com/hc/en-us/articles/360028716472-Server-Banner-Background-Invite-Splash-Image)

If you'd like, you can go update your invite code to something like `discord.gg/<yourprojectname>` and then update it a new PR. Either way, please let me know.

**Pull request merged**
