### PR TITLE
Add YatopiaMC

### PR DESCRIPTION
**Pull request by duplexsystem**
In order to make the review process faster, please take a few minutes to go through this checklist:

## Acceptance Criteria

- All of the following criteria must be met:
  - [x] This community is directly tied to an open source project
  - [x] The open source project has an OSI-approved open source license: https://opensource.org/licenses
  - [x] This Discord server is an official channel for the open source project approved by the maintainers of the open source project
  - [x] This Discord server adheres to the [Discord Community Guidelines](https://discord.com/guidelines)
- One of the following crieria must be met:
  - [x] The Discord server has over 1,000 members
  - [ ] The open source project has a repository with at least 1,000 GitHub Stars or some equivalent

## Code Review

- All of the following criteria must be met:
  - [x] The `"title"` field has a commonly identifiable name of the open source project 
  - [x] The `"logo"` field refers to the correct logo file (double check the extension)
  - [x] The `"quote"` field (if included, it is optional) is about your usage of Discord (and not about the open source project itself)
  - [x] The `"quoteSourceUrl"` field (if included, it is optional) is a fully specified and valid URL starting with `https://`
  - [x] The `"inviteCode"` field contains a valid invite code (without the full URL), without an expiration date
  - [x] The `"githubUrl"` field is a fully specified and valid URL starting with `https://` and refers to a place where we can easily find your primary open source repositories. GitHub repo or organization URLs (or some equivalent) are acceptable (but not a cloning URL).

## Logo Review

- All of the following criteria must be met:
  - [x] The logo makes use of transparent elements and does not include its own background
  - [x] The logo will look correct when the non-transparent elements are made solid white
  - [x] The logo is a commonly identifiable logo of the open source project
- One of the following crieria must be met:
  - [ ] The logo is an SVG file with 72x72 dimensions and has been optimized with [`svgo`](https://www.npmjs.com/package/svgo) ([Web UI](https://jakearchibald.github.io/svgomg/))
  - [x] The logo is a PNG file with 144x144 dimensions and has been optimized with [ImageOptim](https://imageoptim.com/) ([Web UI](https://imageoptim.com/online))

### CODE REVIEW

**Comment by jamiebuilds** [comment]
Turned on some features for you:

- [Vanity Invite URL](https://support.discord.com/hc/en-us/articles/115001542132-Server-Vanity-URLs)
- [Server Banner & Invite Splash](https://support.discord.com/hc/en-us/articles/360028716472-Server-Banner-Background-Invite-Splash-Image)

If you'd like, you can go update your invite code to something like `discord.gg/<yourprojectname>` and then update it in this PR. Either way, please let me know.

**Comment by duplexsystem** [comment]
@jamiebuilds I have updated the PR with a vanity link.

**Review by jamiebuilds — APPROVED** [review]

**Comment by Tim203** [comment]
If Yatopia is getting accepted, then #287 really needs to be re-added. Yatopia is a fork of Paper and more.

**Comment by duplexsystem** [comment]
This server is for more than just our paper fork but yes I agree paper should be readded.

**Comment by Tim203** [comment]
I'm not here to discuss this (since this is not really the place for it), but Yatopia is basically a collection of things from other forks.

**Comment by duplexsystem** [comment]
It's one of our OSS projects yes.

**Comment by lukeeey** [comment]
This is unfair that a (barely popular) fork that simply combines other peoples work (Figure 1) gets accepted but Paper has been waiting for months 

Figure 1:
image

**Comment by duplexsystem** [comment]
Yes, we merge code from other repos and apply out own on top. And I do agree paper should be merged so I don't know what your getting at.

**Comment by Chew** [comment]
I do agree with luke's (now deleted) comment. A repository that relies heavily on code from other projects should also have the child projects added too. Just doesn't seem fair a repo can get added here solely because combined code and occasionally fixes bugs they come across. That being said, neither project is currently added, so there's no reason for a debate (yet).

**Comment by duplexsystem** [comment]
Paper relies on code from spigot and applies it's own stuff, just on a larger scale. And agian I agree Paper should be added.

**Comment by Tim203** [comment]
Please, don't act like Yatopia really adds anything on itself. I've also had this discussion with you on discord (since once again) I don't really think it's relevant to say it here. Paper is clearly more than just Spigot

**Comment by Titaniumtown** [comment]
Yatopia does add things on itself. But I really don't see how this conversation is relevant at all. I too agree that the PaperMC discord server should get readded. But I don't see how this prevents the merging of this PR as that would be a completely separate discussion more suited for #287.

**Comment by Tim203** [comment]
Apologies for being so direct earlier on. I only wanted to say that I would reconsider what should and what shouldn't be on the open source list. I would add Paper (see #287), but I personally wouldn't have added Tuinity.

**Comment by jamiebuilds** [comment]
This is not the place to resolve inter-project disputes. Speaking for myself as an open source maintainer, I don't appreciate it. 

I am sorry I have not re-added PaperMC, it was not an intentional slight against anyone. I had put this project on pause while I worked on automating the review process in my spare time. But then I accidentally triggered an influx of PRs in the last few days and it's taken a lot of my time to catch up and go back and forth on PRs.

**Pull request closed without merging**
