### PR TITLE
feat: added ajour

### PR DESCRIPTION
**Pull request by casperstorm**
Added description and logo for Ajour ✨

### CODE REVIEW

**Comment by jamiebuilds** [comment]
Turned on some features for you:

- [Vanity Invite URL](https://support.discord.com/hc/en-us/articles/115001542132-Server-Vanity-URLs)
- [Server Banner & Invite Splash](https://support.discord.com/hc/en-us/articles/360028716472-Server-Banner-Background-Invite-Splash-Image)

Do you want to update your invite code to something like `discord.gg/<yourprojectname>`?

**Comment by casperstorm** [comment]
> Turned on some features for you:
> 
> 
> 
> - [Vanity Invite URL](https://support.discord.com/hc/en-us/articles/115001542132-Server-Vanity-URLs)
> 
> - [Server Banner & Invite Splash](https://support.discord.com/hc/en-us/articles/360028716472-Server-Banner-Background-Invite-Splash-Image)
> 
> 
> 
> Do you want to update your invite code to something like `discord.gg/<yourprojectname>`?

Thank you so much!
A invite code like `getajour` could be cool if possible.

**Comment by jamiebuilds** [comment]
I can't change your vanity code for you, you'll have to go do that in-app:

https://support.discord.com/hc/en-us/articles/115001542132-Server-Vanity-URLs

**Comment by casperstorm** [comment]
> I can't change your vanity code for you, you'll have to go do that in-app:
> 
> https://support.discord.com/hc/en-us/articles/115001542132-Server-Vanity-URLs

Thanks, I got it updated and pushed the changes here. Thank you so much.

**Review by jamiebuilds — APPROVED** [review]

**Pull request closed without merging**
